module.exports = {
  apps: [
    {
      name: "api-1",
      script: "./main.js",
      watch: true,
      env: {
        PORT: 3000,
        NODE_ENV: "production",
        TV_FILE_M3U8: "./src/files",
        ALGOLIA_CLIENT: "",
        ALGOLIA_INDEX: "",
        ALGOLIA_KEY: "",
        REDIS_URL: "",
        PG_USER: "",
        PG_PASS: "",
        PG_DB: "",
        PG_HOST: "",
        PG_PORT: "",
        URL: "",
        DOCS: "",
      }
    },
    {
      name: "api-2",
      script: "./main.js",
      watch: true,
      env: {
        PORT: 3001,
        NODE_ENV: "production",
        TV_FILE_M3U8: "./src/files",
        ALGOLIA_CLIENT: "",
        ALGOLIA_INDEX: "",
        ALGOLIA_KEY: "",
        REDIS_URL: "",
        PG_USER: "",
        PG_PASS: "",
        PG_DB: "",
        PG_HOST: "",
        PG_PORT: "",
        URL: "",
        DOCS: "",
      }
    },
    {
      name: "api-3",
      script: "./main.js",
      watch: true,
      env: {
        PORT: 3002,
        NODE_ENV: "production",
        TV_FILE_M3U8: "./src/files",
        ALGOLIA_CLIENT: "",
        ALGOLIA_INDEX: "",
        ALGOLIA_KEY: "",
        REDIS_URL: "",
        PG_USER: "",
        PG_PASS: "",
        PG_DB: "",
        PG_HOST: "",
        PG_PORT: "",
        URL: "",
        DOCS: "",
      }
    },
    {
      name: "api-4",
      script: "./main.js",
      watch: true,
      env: {
        PORT: 3003,
        NODE_ENV: "production",
        TV_FILE_M3U8: "./src/files",
        ALGOLIA_CLIENT: "",
        ALGOLIA_INDEX: "",
        ALGOLIA_KEY: "",
        REDIS_URL: "",
        PG_USER: "",
        PG_PASS: "",
        PG_DB: "",
        PG_HOST: "",
        PG_PORT: "",
        URL: "",
        DOCS: "",
      }
    },
    {
      name: "api-5",
      script: "./main.js",
      watch: true,
      env: {
        PORT: 3004,
        NODE_ENV: "production",
        TV_FILE_M3U8: "./src/files",
        ALGOLIA_CLIENT: "",
        ALGOLIA_INDEX: "",
        ALGOLIA_KEY: "",
        REDIS_URL: "",
        PG_USER: "",
        PG_PASS: "",
        PG_DB: "",
        PG_HOST: "",
        PG_PORT: "",
        URL: "",
        DOCS: "",
      },
    },
  ],
};
