version: '3'
services:
  redis:
    image: redis:latest
    container_name: queroassistir-redis
    ports:
      - '6379:6379'
  postgres:
    image: postgres:latest
    container_name: queroassistir-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
